/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 11 21:54:41 GMT 2019
 */

package org.apache.commons.math4.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.exception.MathIllegalNumberException;
import org.apache.commons.math4.exception.NotFiniteNumberException;
import org.apache.commons.math4.exception.util.Localizable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NotFiniteNumberException_ESTest extends NotFiniteNumberException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = MathIllegalNumberException.INTEGER_ZERO;
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = (Object) objectArray0;
      NotFiniteNumberException notFiniteNumberException0 = null;
      try {
        notFiniteNumberException0 = new NotFiniteNumberException(integer0, objectArray0);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = MathIllegalNumberException.INTEGER_ZERO;
      Object[] objectArray0 = new Object[6];
      Localizable localizable0 = mock(Localizable.class, new ViolatedAssumptionAnswer());
      NotFiniteNumberException notFiniteNumberException0 = new NotFiniteNumberException(localizable0, integer0, objectArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = MathIllegalNumberException.INTEGER_ZERO;
      Object[] objectArray0 = new Object[6];
      NotFiniteNumberException notFiniteNumberException0 = new NotFiniteNumberException(integer0, objectArray0);
  }
}
